# Generated by Django 5.2.12 on 2026-04-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='not_interested_posts',
            field=models.ManyToManyField(related_name='not_interested_users', to='blog.post'),
        ),
    ]
