# Generated by Django 5.2.12 on 2026-04-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profile_not_interested_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='not_interested_posts',
            field=models.ManyToManyField(related_name='user_not_interested_posts', to='blog.post'),
        ),
    ]
